[package]
name = "wayland-client"
version = "0.9.9"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to the standard C implementation of the wayland protocol, client side."
build = "build.rs"

[badges]
travis-ci = { repository = "smithay/wayland-rs" }

[dependencies]
wayland-sys = { version = "0.9.9", features = ["client"], path = "../wayland-sys" }
libc = "0.2"
bitflags = "1"

[build-dependencies]
wayland-scanner = { version = "0.9.9", path = "../wayland-scanner" }

[dev-dependencies]
byteorder = "0.5"
tempfile = "2"

[features]
default = ["egl", "cursor"]
dlopen = ["wayland-sys/dlopen"]
egl = ["wayland-sys/egl"]
cursor = ["wayland-sys/cursor"]

