[package]
name = "wayland-protocols"
version = "0.9.9"
documentation = "https://smithay.github.io/wayland-rs/wayland_protocols/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
keywords = ["wayland", "client", "server", "protocol", "extension"]
description = "Generated API for the officials wayland protocol extensions"
build = "build.rs"
categories = ["gui", "api-bindings"]

[badges]
travis-ci = { repository = "smithay/wayland-rs" }

[dependencies]
wayland-sys = { version = "0.9.9", path = "../wayland-sys" }
wayland-client = { version = "0.9.9", path = "../wayland-client", optional = true, default-features = false }
wayland-server = { version = "0.9.9", path = "../wayland-server", optional = true }
bitflags = "1"

[build-dependencies]
wayland-scanner = { version = "0.9.9", path = "../wayland-scanner" }

[features]
client = ["wayland-client"]
server = ["wayland-server"]
unstable_protocols = []

